name: Test EasyOCR

on:
  push:
    branches:
      - main
      - ci
      - release/*
      - feature/*
    tags:
      - v*
    paths-ignore:
      - README*
  pull_request:

jobs:
  test_linux:
    name: Test ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.11"
            tesseract5: true
          - os: ubuntu-latest
            python: "3.12"
            tesseract5: true
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: "0"

      - name: Install Tesseract 5
        if: matrix.tesseract5
        run: |
          sudo add-apt-repository -y ppa:alex-p/tesseract-ocr-devel

      - name: Install common packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            curl \
            ghostscript \
            img2pdf \
            libexempi8 \
            libffi-dev \
            libsm6 libxext6 libxrender-dev \
            pngquant \
            poppler-utils \
            tesseract-ocr \
            tesseract-ocr-deu \
            tesseract-ocr-eng \
            tesseract-ocr-osd \
            unpaper \
            zlib1g

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Cache EasyOCR models
        uses: actions/cache@v5
        with:
          path: ~/.EasyOCR
          key: easyocr-models-${{ runner.os }}

      - name: Install Python packages
        run: uv sync --group test --python ${{ matrix.python }}

      - name: Report versions
        run: |
          tesseract --version
          gs --version
          pngquant --version
          unpaper --version
          img2pdf --version

      - name: Test
        run: uv run pytest tests/
